# Generated by Django 3.0.6 on 2020-09-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0005_auto_20200916_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents%Y-%m-%d-%H-%M-%S'),
        ),
        migrations.AlterModelTable(
            name='document',
            table='file',
        ),
    ]
