# Generated by Django 3.0.6 on 2020-10-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0006_auto_20200917_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
