# Generated by Django 3.0.6 on 2020-10-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0007_document_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents'),
        ),
    ]
