# Generated by Django 3.0.6 on 2020-11-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0008_auto_20201027_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
    ]
