# Generated by Django 3.0.6 on 2020-11-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0009_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=models.CharField(blank=True, max_length=255)),
        ),
    ]
