# Generated by Django 3.0.6 on 2021-02-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0011_auto_20201130_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='Files'),
        ),
    ]
