# Generated by Django 3.0.6 on 2021-03-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0012_auto_20210208_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='label_list',
            field=models.CharField(default='Model', max_length=200),
        ),
    ]
