# Generated by Django 3.0.6 on 2021-03-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0014_auto_20210306_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
    ]
