# Generated by Django 3.0.6 on 2021-03-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0015_remove_document_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='label_list',
            new_name='labels',
        ),
    ]
