# Generated by Django 3.0.6 on 2021-03-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0016_auto_20210307_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='labels',
        ),
    ]
