# Generated by Django 3.0.6 on 2021-04-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0017_remove_document_labels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
